### ISSUE TITLE
public url

### ISSUE THREAD

**Issue by morfarpeter** [zodern/minify-js-sourcemaps#1]
Hi,

Cool package. Is there any way just to get the source map public url without setting INLINE_SOURCE_MAPS=true. I just need to be able to download it for Raygun.io, but I don't want my production site to use the sourcemap cause of the increasing filesize :)

I have tried mydomain.com/.production.min.js.map and mydomain.com/[autogenerated id].js.map but can't seem to find it.

Is is possible? 

Cheers
Peter

**Comment by morfarpeter** [comment]
arh.. i think first of all its becuase the file doesn't get generated in my project due to the default max_line_len: 32000 option. Is it possible to set this to 0 (disabled) ? :)

**Comment by zodern** [comment]
The file is in your app's source folder, not in the bundle from running meteor build. For that to work, I will need to be able to add the sourcemap to the public folder, which I don't think Meteor supports for minifieres. Today I will verify that, and if Meteor doesn't I will look for a workaround.

**Comment by zodern** [comment]
I released 2.1.0 which has a few improvements.

It now has a public url, but it changes whenever the js changes. You can get it by looking in `programs/web.browser/program.json` in the bundle. Meteor also sets the `x-sourcemap` header for `app.js` to the public url. I could create a package to add a server route to get the sourcemap at `/app.js.map`.

The location of the source map has changed. It now is in the bundle at `programs/web.browser/app.js.map`.
