### ISSUE TITLE
Use uglify-es 3.3.9

### ISSUE THREAD

**Issue by morloy** [zodern/minify-js-sourcemaps#10]
Just tried the package with Meteor 1.7 and it fails. Downgrading `uglify-es` to `3.3.9` solves the issue. [Meteor did the same](https://github.com/meteor/meteor/commit/7b06c6043a70699de1d32478474c206f1446c743)

Btw, `uglify-es` doesn’t throw errors itself. [You need to do that explicitly](https://github.com/mishoo/UglifyJS2#api-reference) using `if (minified.error) throw minified.error;`

**Comment by zodern** [comment]
This is fixed in  zodern:standard-minifier-js@2.5.0.
