### ISSUE TITLE
map file contains some garbage

### ISSUE THREAD

**Issue by hexsprite** [zodern/minify-js-sourcemaps#16]
I've been working around this issue for some time now but I'd like to be able to use this without workaround.

After the map is built there is a single line of "garbage" that I must manually remove before the map is usable.

It's basically a single like with what looks like the closing part of JSON: `)]}'`

The rest of the file then follows. If I remove that first line all is good otherwise but it means my build has an extra step.

Here's fuller example..

```
)]}'
{"version":3,"sources":["meteor://💻app/0","meteor://💻app/packages/random/random.js","meteor://💻app/packages/random/deprecated.js","meteor://💻app/packages/ejson/ejson.js","meteor://💻app/packages/ejso....... <rest of file continues>
```

**Comment by zodern** [comment]
Hi @hexsprite,

It seems that line is added to prevent XSSI attacks: https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.h7yy76c5il9v

Are you using a tool or service that doesn't support that line?

**Comment by hexsprite** [comment]
Thanks, good to know. It may be that when I was initially testing this package I tried some kind of source map validation using an npm module but it didn't understand that so I thought it was broken. I will try it with my error tracking service and find out.

**Comment by hexsprite** [comment]
Just tested it with Rollbar service which I use and it works fine. Thanks for the info.
