### ISSUE TITLE
Sourcemaps mapping to wrong location in file

### ISSUE THREAD

**Issue by emaciel10** [zodern/minify-js-sourcemaps#18]
I am experiencing a strange issue when attempting to use this package. It looks like the source maps are pointing to the wrong location within the file when an error is thrown. I have spent a decent amount of time tracking this down to see if it was something specific to our project but even after stripping out nearly all of our code I am still seeing the issue. I think it might have something to do with our directory structure but I am really not sure. I have created a sample reproduction here:
https://github.com/hiveteams/zodern-minify-reproduction

Do you have any idea what might be causing this?

We are currently using Meteor 1.7.0.3, zodern:minifier-js@2.5.0, and zodern:standard-minifier-js@2.6.0.

Thanks!

**Comment by zodern** [comment]
Thanks for creating a reproduction. Is the repository private?

**Comment by etyp** [comment]
@zodern it's public now :)

**Comment by zodern** [comment]
I tried it, and was unable to reproduce the problem. Are you using the error stack trace to check if the source maps are correct? Which web browser and operating system are you using?

If it is due to your directory structure, updating to zodern:standard-minifier-js@3.0.0 might fix it.

**Comment by etyp** [comment]
@elm2178 we confirmed it doesn't work by forcing an error and looking at sentry right? Or did we do it some other way?

**Comment by emaciel10** [comment]
@zodern yeah we were testing the production source maps and seeing if we could get everything to work with sentry. We were triggering the errors and then viewing the mapped positions in sentry. Here is where the source map was pointing to on version 2.6.0:

![image](https://user-images.githubusercontent.com/11020939/46503272-5b288880-c7f8-11e8-9469-bee31b631177.png)

I updated to zodern:standard-minifier-js@3.0.0 and zodern:minifier-js@3.0.0 and this resolved the issue. Now the source map is pointing to the correct location:

![image](https://user-images.githubusercontent.com/11020939/46503237-43510480-c7f8-11e8-9ba9-2c4213ad9c2c.png)

Thanks!

**Comment by zodern** [comment]
Thanks @elm2178 for the details. I'm glad that was all that was needed to fix it.
