### ISSUE TITLE
Sourcemaps are missing lines

### ISSUE THREAD

**Issue by Slind14** [zodern/minify-js-sourcemaps#25]
With the introduction of the cache feature, source maps are missing lines. When one is converting a stack trace most of the time only one or two lines could be mapped since the other ones are missing.

**Comment by rebane2001** [comment]
Fixed in #30.

**Comment by zodern** [comment]
The problem probably is due to some packages missing source maps. I'm fixing this in Meteor 3, but #33 also has a more hacky fix in the minifier where it tries to create source maps for these packages.
