### ISSUE TITLE
Malformed source map

### ISSUE THREAD

**Issue by copleykj** [zodern/minify-js-sourcemaps#27]
After adding this package it seems the the source map that gets built contains characters at the beginning of the file that don't belong there. Specifically these characters `)]}'`. I'm not sure if running with the --production flag has anything to do with this.

Including source map for reference.

[f38258f8665e78a9bdd8c3984e55678e546e9c1c.txt](https://github.com/zodern/minify-js-sourcemaps/files/7248900/f38258f8665e78a9bdd8c3984e55678e546e9c1c.txt)

**Comment by zodern** [comment]
The [source map specification](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.h7yy76c5il9v) suggests adding those characters to prevent XSSI attacks. Most source maps have them, and they are supported by most browsers and tools that work with source maps.

**Comment by copleykj** [comment]
Oh! Really interesting... It's weird then that lighthouse complains about it.. I'll see if I can dig deeper and see if the problem lies in lighthouse.
