### ISSUE TITLE
Error: Path reservation conflict: app.js

### ISSUE THREAD

**Issue by elie222** [zodern/minify-js-sourcemaps#3]
When adding this package I get this error upon deploy to Galaxy:
```
Error: Path reservation conflict: app.js
    at Builder.reserve (/tools/isobuild/builder.js:333:15)
    at /tools/isobuild/bundler.js:1553:15
    at /tools/isobuild/bundler.js:1545:11
```

**Comment by teknologist** [comment]
Same here

**Comment by teknologist** [comment]
@elie222 Did you solve this ? di you figure out which package was causing this ?

**Comment by zodern** [comment]
This is from dynamic imports. I am releasing an update today that fixes using dynamic imports.

**Comment by teknologist** [comment]
Hi @zodern, so happy to see you are working on it again !

Thanks!

**Comment by zodern** [comment]
The update is now available!
