### ISSUE TITLE
`Errors prevented bundling` in 5.1.0

### ISSUE THREAD

**Issue by radekmie** [zodern/minify-js-sourcemaps#35]
I wanted to give version 5.1.0 a try in our app and here's what happened:

```
Warning: Nested Profile.run at ProjectContext prepareProjectForBuild
Errors prevented bundling:
While minifying app code:
<anonymous>: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)
at packages/fastMinifier_plugin.js:230:22
at Array.forEach (<anonymous>)
at packages/fastMinifier_plugin.js:225:21
at Function.Profile.time (packages/fastMinifier_plugin.js:35:7)
at MeteorBabelMinifier.<anonymous> (packages/fastMinifier_plugin.js:224:11)
at MeteorBabelMinifier.processFilesForBundle
(packages/fastMinifier_plugin.js:31:21)


While minifying app code:
<anonymous>: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)
at packages/fastMinifier_plugin.js:230:22
at Array.forEach (<anonymous>)
at packages/fastMinifier_plugin.js:225:21
at Function.Profile.time (packages/fastMinifier_plugin.js:35:7)
at MeteorBabelMinifier.<anonymous> (packages/fastMinifier_plugin.js:224:11)
at MeteorBabelMinifier.processFilesForBundle
(packages/fastMinifier_plugin.js:31:21)
```

I can't share the code, but if needed, I could dig into it. We're on Meteor 2.5.8.

**Comment by zodern** [comment]
It seems like it is erroring at https://github.com/zodern/minify-js-sourcemaps/blob/12a5ce2e0edfd195da031846e0e0bc6cd56874c7/standard-minifier-js-sourcemaps/plugin/minify-js.js#L217-L218 because the sourcemap is undefined. I'm not sure what could cause that to happen. If you try version 5.1.1, it will log the bundle path of the file with the missing source map.

**Comment by radekmie** [comment]
I just checked it. The error is still there and no additional log appeared. Also, `JSON.parse(undefined)` results in `Uncaught SyntaxError: Unexpected token u in JSON at position 0` (`u`, not `o`); `o` appears when `JSON.parse({})` is executed.

**Comment by zodern** [comment]
Thanks. I missed that it was `o`. I published version 5.1.2 that should fix this, though I haven't been able to figure out why the source map would be an object.

**Comment by alisnic** [comment]
tested and all good in our project. huge thanks for responsiveness!

**Comment by radekmie** [comment]
Thanks, now it works!
```
other Target#minifyJs 37,808ms ->  9,060ms
Total:                99,358ms -> 66,001ms
```

I do see a significant size increase, though - will post it in #37.
