### ISSUE TITLE
CDN friendly file name - for versioning

### ISSUE THREAD

**Issue by hridayeshgupta** [zodern/minify-js-sourcemaps#4]
Fixed name app.js for output file is not friendly with CDNs such cloudfront, akamai. They cache files based on url, and since name of file is not changing, it is highly probable that upon new build of meteor app, for few hours users will get older version of app.js, leading to potential errors.

It would be better to change output filename everytime as meteor does.

**Comment by zodern** [comment]
Cloudflare by default caches on query parameters. 

In version 3, I will use a random name by default, but provide an option to use the current behavior of always using the same file name.

**Comment by teknologist** [comment]
I'll wait for version 3 as we use cloudflare and other stuff that relies on bundle name change to rrigger client update.

**Comment by hridayeshgupta** [comment]
Will wait for version 3.
Caching headers can define different behaviors on browser such as
1. Every time fetching js from server
2. Check with server and fetch only if file has been changed based on etag.
3. Dont call server at all and use cached file.
3rd case doesnt work if name if file has not been changed. In other cases as well we have to added pseudo query param in script(which is automatically added by meteor). So I thought it is much better to have different filenames everytime.

**Comment by zodern** [comment]
With this change, there isn't much difference between the standard minifiers and this package, besides that this one creates sourcemaps. After v3, I will look into creating a PR for meteor.

**Comment by morloy** [comment]
Created a quick fix for this issue. The `/app.js?hash=…` doesn’t work with Meteor’s system for modern and legacy browsers in 1.7.

**Comment by maxpain** [comment]
Any updates?

**Comment by zodern** [comment]
This is now available in version 3.
