### ISSUE TITLE
Minifier lost object contents

### ISSUE THREAD

**Issue by brianlukoff** [zodern/minify-js-sourcemaps#41]
In version 5.1.1, this object definition:
```
var options = { style: 'currency', currency };
```
was minified as an empty object (i.e., the object literal was minified as `{}`).

**Comment by zodern** [comment]
This might be related to https://github.com/swc-project/swc/issues/7739.

**Comment by brianlukoff** [comment]
I think you're right -- we are running into it in exactly the same context. I've rolled back to the previous version for now.

**Comment by 4fox4** [comment]
It seem to be fixed by https://github.com/swc-project/swc/pull/7702 (https://github.com/vercel/next.js/issues/53151#issuecomment-1655734703)
Is a new version planned?

**Comment by ziedmahdi** [comment]
@brianlukoff we are having the same error, what is the version that you downgraded to?

**Comment by brianlukoff** [comment]
@ziedmahdi We're back to using 4.1.1 but that is working well.

**Comment by zodern** [comment]
This should be fixed in version 5.2.0
