### ISSUE TITLE
Client bundle is broken when including total code is too big only on Safari on iOS 16.1

### ISSUE THREAD

**Issue by ToyboxZach** [zodern/minify-js-sourcemaps#42]
is bug report should include:
 The version of Meteor showing the problem.
2.13 also happens on 2.12

 The operating system you're running Meteor on.
iOS simulator 16.1

 The expected behavior.
Client bundle loads, and at worst shows error when we try to import

 The actual behavior.
Client bundle fails to load completely, only on this safari and only with the production bundle
"Duplicate parameter 'n' not allowed in function with default parameter values."

 A simple reproduction! (Must include the Github repository and steps to reproduce the issue on it.)

Making this the client bundle repros it

```
import Base from "@mui/base";
console.log("Log to force loading", Base);
```
It also happens if I include puppeteer, or if I have a large amount of code, even behind dynamic imports

This also still happens if I force this to be the legacy bundle, so its not related to that.

This only happens when including this package

Note I can't repro this in any other browser, even new versions of iOS work fine.

**Comment by radekmie** [comment]
I can confirm the same happened for us now. We've been using `zodern:standard-minifier-js` for a few months now and it suddenly broke. Based on the diff in the builds, I guess it's simply a problem of name mangling (i.e., there's a name conflict).

Let me know if I could help anyhow!

**Comment by zodern** [comment]
I released version 5.2.0 which includes many bug fixes from the swc minifier. Would you mind trying again?

**Comment by ToyboxZach** [comment]
It seems to be resolved thanks!

**Comment by ToyboxZach** [comment]
Hmm, after updating this my production server stopped loading the npm dependencies correctly, would that be at all related to this package?

**Comment by ToyboxZach** [comment]
I actually forgot to test it with the production bundle in general, so this is not resolve at all

**Comment by uuuJ** [comment]
Hey ! Any news on this one ? We're blocked too on ios devices 😞

**Comment by skeetmtp** [comment]
Any news on this topic, as this issue is preventing us from using montiapm (source map issue)

**Comment by brianlukoff** [comment]
We're also seeing the same issue (and same duplicate parameter issue) -- was only an issue when running in old versions of Safari (e.g. 13), but we had to roll back to 4.1.1.

**Comment by zodern** [comment]
#38 is fixed in version 5.3.0. Are these the same issue?

**Comment by ToyboxZach** [comment]
Yep initial test seems to pass, I will want to double check it on a closer to real production environment before I am completely confident in it

**Comment by ToyboxZach** [comment]
Seems to be fixed! Thanks for all the work!

**Comment by brianlukoff** [comment]
Same here -- seems to work now in Safari 13 where the previous version did not -- thanks!

**Comment by skeetmtp** [comment]
Seems ok here too! thanks a lot!
