### ISSUE TITLE
Use uglify-es

### ISSUE THREAD

**Issue by zodern** [zodern/minify-js-sourcemaps#5]
Will reduce the number of files uglify fails on. `babel-minify` should also be configured to create sourcemaps for when `uglify` fails.

**Comment by teknologist** [comment]
Could you also fill the stats data as standard minifier does so we can use it with meteors bundle visualizer?

Thanks!

**Comment by teknologist** [comment]
Also save the .js minified bundle in web.browser instead of app/ to keep as close as possible to meteors defaults.

Would help us as we use an nginx reverse proxy to serve static content...

**Comment by zodern** [comment]
Could you please create two new issues for those changes?

**Comment by teknologist** [comment]
@zodern done. Thanks for your hard work on these!

Cheers!

**Comment by zodern** [comment]
I released zodern:minifier-js@2.2.0 today that switched to using uglify-es.

**Comment by zodern** [comment]
> babel-minify should also be configured to create sourcemaps for when uglify fails.

 This was added in zodern:standard-minifier-js@2.5.0 and zodern:minifier-js@2.4.0.
