### ISSUE TITLE
Fill stats in minifier process to be able to work with meteors bundle visualizer

### ISSUE THREAD

**Issue by teknologist** [zodern/minify-js-sourcemaps#7]
Could you also fill the stats data as standard minifier does so we can use it with meteors bundle visualizer?

Thanks!

**Comment by zodern** [comment]
All of the code is there, it just needs to be uncommented.

The feature uses `babel-compiler`, which had a major version bump in Meteor 1.6. There would either need to be a version published with Meteor 1.5, and a seperate version published with 1.6, or newer versions of this plugin would need to drop dupport for Meteor 1.5 and older.

**Comment by teknologist** [comment]
Brilliant! in the meantime I'll clone and install locally

**Comment by zodern** [comment]
I released an update today that adds bundle stats!
