### ISSUE TITLE
Conditionally allow source maps

### ISSUE THREAD

**Issue by smeijer** [zodern/minify-js-sourcemaps#9]
Would be nice if we could allow the source maps to be exposed, based on an environment variable. General idea:

https://github.com/zodern/minify-js-sourcemaps/blob/master/hide-production-sourcemaps/hide-production-sourcemaps.js

```js
var fileInfo = WebAppInternals.staticFiles;

if (!process.env.EXPOSE_SOURCE_MAPS) {
  Object.keys(WebAppInternals.staticFiles).forEach(function(key) {
    if (key.indexOf(".map") === key.length - ".map".length) {
      delete WebAppInternals.staticFiles[key];
      return;
    }
    WebAppInternals.staticFiles[key].sourceMapUrl = false;
  });
}
```

This way we could debug errors in production by temporarily exposing source maps. I would recommend against doing so in a real production environment. But it would be possible to reuse the production containers and expose source maps without the need for another change / recompile.

**Comment by zodern** [comment]
The `EXPOSE_SOURCE_MAPS` env variable has been added in version 1.2.0.
